<template>
    <div class="h-screen bg-gray-100 my-0">
        <nav class="h-12 relative flex flex-wrap items-center justify-between px-2 py-3 bg-blue-500 mb-3 fade-in">
            <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
                <img src="../assets/pvu.png" alt="" class="h-6" >
            </div>
        </nav>

        <div class="flex justify-center my-12 slide-in-top">
            <img src="../assets/pvu.png" alt="" class="h-32" >
        </div>

        <div class="flex justify-center mb-12 slide-in-bottom">
            <div action="" class="bg-white px-6 py-4 md:w-1/2 w-3/4">
                <h2 class="text-center md:text-3xl text-xl text-gray-400 mt-4 mb-8">Welcome PV</h2>
                
                <div class="block my-4">
                    <label for="discord" class="block text-gray-400 text-sm">Discord</label>
                    <input id="discord" v-model="discord" type="text" class="w-full h-10 py-2 px-2 border-2 border-gray-300 rounded-md">
                
                </div>

                <div class="block my-4">
                    <label for="user" class="block text-gray-400 text-sm">User</label>
                    <input id="user" v-model="user" type="text" class="w-full h-10 py-2 px-2 border-2 border-gray-300 rounded-md">
                
                </div>
                
                <div class="block my-4">
                    <label for="password" class="block text-gray-400 text-sm">Password</label>
                    <input id="password" v-model="password" type="password" class="w-full h-10 py-2 px-2 border-2 border-gray-300 rounded-md">
                </div>

                <button class="bg-blue-500 h-10 text-gray-100 py-2 px-4 w-full rounded-md bold" @click="registrar()">Register</button>
                
            </div>
        </div>

        <footer class="text-center">
            <div class="absolute inset-x-0 bottom-0 h-16 text-center">
                <span class="text-gray-600 text-xs text-center">ChadGeners</span>
            </div>
        </footer>
    </div>
</template>

<script>
import firebase from 'firebase'
import donorServices from '../services/donor.services.js'
export default {
    data() {
        return {
            discord: "",
            user: "",
            password: "",
        };
    },
    name: "Basic",

    methods: {
        registrar() {
      if (this.user && this.password) {
        firebase.auth().createUserWithEmailAndPassword(this.user, this.password)
        .then(() => {
            let donor = {
              discord: this.discord,
              uid: firebase.auth().currentUser.uid,
              active: true,
              license: 1
            };
            localStorage.setItem('user', donor.uid);
            donorServices.postDonor(donor);
            this.$router.push('/');
          })
          .catch((err) => {
              console.log(err);
          });
      }
    },
    },
};
</script>

<style>
.fade-in {
	-webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-8-29 17:11:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

.slide-in-top {
	-webkit-animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-8-29 17:7:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}

.slide-in-bottom {
	-webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	animation: slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-8-29 17:10:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
            transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
            transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
</style>